apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-ampq-protocol
spec:
  type: NodePort
  ports:
    - port: 3410
      targetPort: 5672
      nodePort: 31600
  selector:
    app: rabbitmq-server
