apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-http-service
spec:
  type: NodePort
  ports:
    - port: 3400
      targetPort: 15672
      nodePort: 31500
  selector:
    app: rabbitmq-server
