apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-server
  labels:
    app: rabbitmq-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-server
  template:
    metadata:
      labels:
        app: rabbitmq-server
    spec:
      #Volumem persistente
      volumes:
        - name: rabbitmq-storage
          persistentVolumeClaim:
            claimName: rabbitmq-pv-claim
      containers:
        - name: rabbitmq-server
          image: 'rabbitmq:3.6-management-alpine'
          ports:
            - containerPort: 15672
              name: http
            - containerPort: 5672
              name: amqp
            #- containerPort: 15692
              #name: prometheus
          volumeMounts:
            - name: rabbitmq-storage
              mountPath: "/mnt/data/"
